apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-deployment
  namespace: dev
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-app-pod
  template:
    metadata:
      labels:
        app: dev-app-pod
    spec:
      containers:
      - name: dev-app-container
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
          name: http-web-svc
