apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev
spec:
  selector:
    app: dev-app-pod
  ports:
    - protocol: TCP
      port: 8888
      targetPort: http-web-svc
      nodePort: 30010
  type: NodePort
